schema_version = "1.0.0"

id = "molecularnodes"
version = "0.0.9"
name = "NodePad"
tagline = "Create beautiful documentation for your node groups"
maintainer = "Brady Johnston<brady.johnston@me.com>"
type = "add-on"
website = "https://bradyajohnston.github.io/nodepad"
tags = [
	"Geometry Nodes"
]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later"
]
copyright =[
	"2024 Brady Johnston",
]