on:
  push:
    branches:
      - main

jobs:
    pypi-publish:
      name: Upload release to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/nodepad
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
           python-version: '3.11'
        - name: Install uv
          uses: astral-sh/setup-uv@v4
          with:
            version: "latest"
        - name: build
          run: |
            uv build
        - name: Publish package distributions to PyPI  
          uses: pypa/gh-action-pypi-publish@release/v1