name: docs-build-deploy

on:
  push:
    branches: ["main"]

jobs:
  build-docs:
    runs-on: macos-14
    permissions: write-all
    env:
      version: 4.3
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/setup-python@v5
        with:
            python-version: "3.11.7"
            cache: pip
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
            version: "latest"

      - name: Generate Node Docs
        run: |
          curl -L -o blender.dmg https://download.blender.org/release/Blender${{ env.version }}/blender-${{ env.version }}.0-macos-arm64.dmg
          hdiutil attach blender.dmg
          cp -R /Volumes/Blender/Blender.app /Applications/
          hdiutil detach /Volumes/Blender
          /Applications/Blender.app/Contents/MacOS/Blender -b -P tests/python.py -- -m pip install -e .
          /Applications/Blender.app/Contents/MacOS/Blender -b -P docs/generate.py

      - name: Build Docs
        run: |
            uv venv --python=3.11
            source .venv/bin/activate
            uv pip install -r pyproject.toml --all-extras
            uv pip install -e .
            cd docs
            quartodoc build
            quarto render


      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
            target: gh-pages
            path: docs
            render: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
