name: Run Tests

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ["4.2", "4.3"]
              os: [macos-14]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: 3.11.7
                cache: pip
            - name: Test in Blender MacOS ARM
              if: matrix.os == 'macos-14'
              run: |
                curl -L -o blender.dmg https://download.blender.org/release/Blender${{ matrix.version }}/blender-${{ matrix.version }}.0-macos-arm64.dmg
                hdiutil attach blender.dmg
                cp -R /Volumes/Blender/Blender.app /Applications/
                hdiutil detach /Volumes/Blender
                /Applications/Blender.app/Contents/MacOS/Blender -b -P tests/python.py -- -m pip install uv
                /Applications/Blender.app/Contents/MacOS/Blender -b -P tests/python.py -- -m uv pip install -r pyproject.toml --extra=test 
            
            - name: Run tests in Blender
              run: |
                /Applications/Blender.app/Contents/MacOS/Blender -b -P tests/python.py -- -m uv pip run pytest -v --cov=nodepad --cov-report=xml:coverage.xml
    
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              if: matrix.os == 'macos-14' && matrix.version == '4.2'
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                name: coverage.xml

            - name: Upload coverage reports to Codecov
              if: matrix.os == 'maxos-14' && matrix.version == '4.2'
              uses: codecov/codecov-action@v3
    
